spring:
  application:
    name: provider                # 应用名称
  profiles:
    active:
      - "@activated.profile@" # 从 maven parent 的配置中 获取值
  # 安全认证
#  security:
#    user:
#      name: root       # 用户名
#      password: 123456 # 密码

server:
  port: 7070                  # 端口

# 注册中心
eureka:
  instance:
    hostname: provider          # 主机名
    prefer-ip-address: true   # 使用 IP 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

  client:
    register-with-eureka: true  # 是否将自己注册到注册中心，默认 true ，集群时要为 true，相互注册
    fetch-registry: true        # 是否从注册中线获取注册信息，默认为 true
    service-url:                 # 注册中心对外暴露的注册地址
      defaultZone: http://root:123456@localhost:8762/eureka/,http://root:123456@localhost:8761/eureka/

#  server:
#    enable-self-preservation: false # true 开启自我保护， false 关闭自我保护
#    eviction-interval-timer-in-ms: 60000 # 清除隔离（单位：毫秒） 默认 60 * 1000

# 度量指标监控与健康检查
management:
  endpoints:
    web:
      exposure:
        include: shutdown   # 开启 shutdown 端点访问
  endpoint:
    shutdown:
      enabled: true # 开启 shutdown 实现优雅停服